#!/usr/bin/env python3

import os
os.system("pip install requests tk simple-colors")
currdir = os.path.dirname(os.path.abspath(__file__))
output_dir = os.path.join(currdir, 'output-files')
if not os.path.exists(output_dir):
    os.mkdir(output_dir)